//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Model", "Weather_OwnerNew_fk", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Individuelltarbeteaspmvc.Models.User), "Weather", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Individuelltarbeteaspmvc.Models.Weather), true)]

#endregion

namespace Individuelltarbeteaspmvc.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ss222enProjectEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ss222enProjectEntities1 object using the connection string found in the 'ss222enProjectEntities1' section of the application configuration file.
        /// </summary>
        public ss222enProjectEntities1() : base("name=ss222enProjectEntities1", "ss222enProjectEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ss222enProjectEntities1 object.
        /// </summary>
        public ss222enProjectEntities1(string connectionString) : base(connectionString, "ss222enProjectEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ss222enProjectEntities1 object.
        /// </summary>
        public ss222enProjectEntities1(EntityConnection connection) : base(connection, "ss222enProjectEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Weather> Weathers
        {
            get
            {
                if ((_Weathers == null))
                {
                    _Weathers = base.CreateObjectSet<Weather>("Weathers");
                }
                return _Weathers;
            }
        }
        private ObjectSet<Weather> _Weathers;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Weathers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToWeathers(Weather weather)
        {
            base.AddObject("Weathers", weather);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="token">Initial value of the token property.</param>
        /// <param name="link">Initial value of the link property.</param>
        public static User CreateUser(global::System.Int32 id, global::System.String name, global::System.String token, global::System.String link)
        {
            User user = new User();
            user.ID = id;
            user.name = name;
            user.token = token;
            user.link = link;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String token
        {
            get
            {
                return _token;
            }
            set
            {
                OntokenChanging(value);
                ReportPropertyChanging("token");
                _token = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("token");
                OntokenChanged();
            }
        }
        private global::System.String _token;
        partial void OntokenChanging(global::System.String value);
        partial void OntokenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String link
        {
            get
            {
                return _link;
            }
            set
            {
                OnlinkChanging(value);
                ReportPropertyChanging("link");
                _link = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("link");
                OnlinkChanged();
            }
        }
        private global::System.String _link;
        partial void OnlinkChanging(global::System.String value);
        partial void OnlinkChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "Weather_OwnerNew_fk", "Weather")]
        public EntityCollection<Weather> Weathers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Weather>("Model.Weather_OwnerNew_fk", "Weather");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Weather>("Model.Weather_OwnerNew_fk", "Weather", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="Weather")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Weather : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Weather object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="owner">Initial value of the owner property.</param>
        public static Weather CreateWeather(global::System.Int32 id, global::System.Int32 owner)
        {
            Weather weather = new Weather();
            weather.ID = id;
            weather.owner = owner;
            return weather;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String place
        {
            get
            {
                return _place;
            }
            set
            {
                OnplaceChanging(value);
                ReportPropertyChanging("place");
                _place = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("place");
                OnplaceChanged();
            }
        }
        private global::System.String _place;
        partial void OnplaceChanging(global::System.String value);
        partial void OnplaceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> longitude
        {
            get
            {
                return _longitude;
            }
            set
            {
                OnlongitudeChanging(value);
                ReportPropertyChanging("longitude");
                _longitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("longitude");
                OnlongitudeChanged();
            }
        }
        private Nullable<global::System.Int32> _longitude;
        partial void OnlongitudeChanging(Nullable<global::System.Int32> value);
        partial void OnlongitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> latitude
        {
            get
            {
                return _latitude;
            }
            set
            {
                OnlatitudeChanging(value);
                ReportPropertyChanging("latitude");
                _latitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("latitude");
                OnlatitudeChanged();
            }
        }
        private Nullable<global::System.Int32> _latitude;
        partial void OnlatitudeChanging(Nullable<global::System.Int32> value);
        partial void OnlatitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> day1day
        {
            get
            {
                return _day1day;
            }
            set
            {
                Onday1dayChanging(value);
                ReportPropertyChanging("day1day");
                _day1day = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("day1day");
                Onday1dayChanged();
            }
        }
        private Nullable<global::System.DateTime> _day1day;
        partial void Onday1dayChanging(Nullable<global::System.DateTime> value);
        partial void Onday1dayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> day1temp
        {
            get
            {
                return _day1temp;
            }
            set
            {
                Onday1tempChanging(value);
                ReportPropertyChanging("day1temp");
                _day1temp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("day1temp");
                Onday1tempChanged();
            }
        }
        private Nullable<global::System.Int32> _day1temp;
        partial void Onday1tempChanging(Nullable<global::System.Int32> value);
        partial void Onday1tempChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> day2day
        {
            get
            {
                return _day2day;
            }
            set
            {
                Onday2dayChanging(value);
                ReportPropertyChanging("day2day");
                _day2day = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("day2day");
                Onday2dayChanged();
            }
        }
        private Nullable<global::System.DateTime> _day2day;
        partial void Onday2dayChanging(Nullable<global::System.DateTime> value);
        partial void Onday2dayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> day2temp
        {
            get
            {
                return _day2temp;
            }
            set
            {
                Onday2tempChanging(value);
                ReportPropertyChanging("day2temp");
                _day2temp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("day2temp");
                Onday2tempChanged();
            }
        }
        private Nullable<global::System.Int32> _day2temp;
        partial void Onday2tempChanging(Nullable<global::System.Int32> value);
        partial void Onday2tempChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> day3day
        {
            get
            {
                return _day3day;
            }
            set
            {
                Onday3dayChanging(value);
                ReportPropertyChanging("day3day");
                _day3day = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("day3day");
                Onday3dayChanged();
            }
        }
        private Nullable<global::System.DateTime> _day3day;
        partial void Onday3dayChanging(Nullable<global::System.DateTime> value);
        partial void Onday3dayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> day3temp
        {
            get
            {
                return _day3temp;
            }
            set
            {
                Onday3tempChanging(value);
                ReportPropertyChanging("day3temp");
                _day3temp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("day3temp");
                Onday3tempChanged();
            }
        }
        private Nullable<global::System.Int32> _day3temp;
        partial void Onday3tempChanging(Nullable<global::System.Int32> value);
        partial void Onday3tempChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> day4day
        {
            get
            {
                return _day4day;
            }
            set
            {
                Onday4dayChanging(value);
                ReportPropertyChanging("day4day");
                _day4day = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("day4day");
                Onday4dayChanged();
            }
        }
        private Nullable<global::System.DateTime> _day4day;
        partial void Onday4dayChanging(Nullable<global::System.DateTime> value);
        partial void Onday4dayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> day4temp
        {
            get
            {
                return _day4temp;
            }
            set
            {
                Onday4tempChanging(value);
                ReportPropertyChanging("day4temp");
                _day4temp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("day4temp");
                Onday4tempChanged();
            }
        }
        private Nullable<global::System.Int32> _day4temp;
        partial void Onday4tempChanging(Nullable<global::System.Int32> value);
        partial void Onday4tempChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> day5day
        {
            get
            {
                return _day5day;
            }
            set
            {
                Onday5dayChanging(value);
                ReportPropertyChanging("day5day");
                _day5day = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("day5day");
                Onday5dayChanged();
            }
        }
        private Nullable<global::System.DateTime> _day5day;
        partial void Onday5dayChanging(Nullable<global::System.DateTime> value);
        partial void Onday5dayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> day5temp
        {
            get
            {
                return _day5temp;
            }
            set
            {
                Onday5tempChanging(value);
                ReportPropertyChanging("day5temp");
                _day5temp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("day5temp");
                Onday5tempChanged();
            }
        }
        private Nullable<global::System.Int32> _day5temp;
        partial void Onday5tempChanging(Nullable<global::System.Int32> value);
        partial void Onday5tempChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 owner
        {
            get
            {
                return _owner;
            }
            set
            {
                OnownerChanging(value);
                ReportPropertyChanging("owner");
                _owner = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("owner");
                OnownerChanged();
            }
        }
        private global::System.Int32 _owner;
        partial void OnownerChanging(global::System.Int32 value);
        partial void OnownerChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model", "Weather_OwnerNew_fk", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Model.Weather_OwnerNew_fk", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Model.Weather_OwnerNew_fk", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("Model.Weather_OwnerNew_fk", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("Model.Weather_OwnerNew_fk", "User", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
