//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Väderapplikation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewUser
    {
        public NewUser()
        {
            this.NewWeathers = new HashSet<NewWeather>();
        }
    
        public int ID { get; set; }
        public string name { get; set; }
        public string token { get; set; }
        public string link { get; set; }
    
        public virtual ICollection<NewWeather> NewWeathers { get; set; }
    }
}
